# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yellow_rounds(object):
    def setupUi(self, Yellow_rounds):
        Yellow_rounds.setObjectName("Yellow_rounds")
        Yellow_rounds.resize(393, 381)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Yellow_rounds.setPalette(palette)
        self.btn_paint = QtWidgets.QPushButton(Yellow_rounds)
        self.btn_paint.setGeometry(QtCore.QRect(120, 250, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_paint.setFont(font)
        self.btn_paint.setObjectName("btn_paint")

        self.retranslateUi(Yellow_rounds)
        QtCore.QMetaObject.connectSlotsByName(Yellow_rounds)

    def retranslateUi(self, Yellow_rounds):
        _translate = QtCore.QCoreApplication.translate
        Yellow_rounds.setWindowTitle(_translate("Yellow_rounds", "Рисование желтых кругов"))
        self.btn_paint.setText(_translate("Yellow_rounds", "Нажать"))
